services:
  postgres:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: capturedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: NnYj6iAVl0YvrKj7EH2u
      POSTGRES_PORT: 5432
      POSTGRES_HOST_AUTH_METHOD: trust
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes: 
      - "./scripts/database/postgres-init.sh:/docker-entrypoint-initdb.d/postgres-init.sh"
      - postgres_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all", "-p", "5432"]
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 120s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: